print('Desafio 4')
a = input('Digite algo:')
print('O tipo primitivo desse valor e', type(a))
print('E alfabetico ?', a.isalpha())
print('E um numero?', a.isnumeric())
print('E alfanumerico?', a.isalnum())
print('So tem espacos?', a.isspace())
print('Esta em menusculas?', a.islower())
print('Esta em maiusculas?', a.isupper())
print('Esta capitalizado?', a.istitle())
