n = int(input(" Digite um numero pra saber a sua taboada:"))
print("A taboada de {}".format(n))
print("=" * 15)
print("{} x {} = {}".format(n, 1, n * 1))
print("{} x {} = {}".format(n, 2, n * 2))
print("{} x {} = {}".format(n, 3, n * 3))
print("{} x {} = {}".format(n, 4, n * 4))
print("{} x {} = {}".format(n, 5, n * 5))
print("{} x {} = {}".format(n, 6, n * 6))
print("{} x {} = {}".format(n, 7, n * 7))
print("{} x {} = {}".format(n, 8, n * 8))
print("{} x {} = {}".format(n, 9, n * 9))
print("{} x {} = {}".format(n, 10, n * 10))
print("{} x {} = {}".format(n, 11, n * 11))
print("{} x {} = {}".format(n, 12, n * 12))
print("{} x {} = {}".format(n, 13, n * 13))
print("{} x {} = {}".format(n, 14, n * 14))
print("{} x {} = {}".format(n, 15, n * 15))
print("{} x {} = {}".format(n, 16, n * 16))
print("{} x {} = {}".format(n, 17, n * 17))
print("{} x {} = {}".format(n, 18, n * 18))
print("{} x {} = {}".format(n, 19, n * 19))
print("{} x {} = {}".format(n, 20, n * 20))
print("{} x {} = {}".format(n, 21, n * 21))
print("{} x {} = {}".format(n, 22, n * 22))
print("=" * 15)


